#!/bin/sh

if [ ! -d /var/log/scavenger/capture/pcap ]; then
	mkdir -p /var/log/scavenger/capture/pcap
	chown nobody.nogroup /var/log/scavenger/capture/pcap
fi

exec /usr/bin/setuidgid nobody /usr/bin/multilog t s5000000 /var/log/scavenger/capture/pcap
