#!/bin/sh

export ETC=/opt/scavenger/etc

PYTHONS="python25 python2.5 python"

for P in `echo $PYTHONS`;
do
	PYTHON=`which $P 2> /dev/null`
	if [ ! -z "$PYTHON" ]; then
		break
	fi
done

if [ -z "$PYTHON" ]; then
	echo "no python intepreter found"
	sleep 10
fi

cd /opt/scavenger

#	strace -vfF -o ./strace.txt \
#	/usr/bin/softlimit -m 15000000 \

exec \
	env \
		debug="0" \
		port="25254" \
		timeout=60 \
		database="/opt/scavenger/db/action_netfilter" \
		mta="82.219.2.81:25" \
		ports="25 587" \
		table="nat" \
		chain="PREROUTING" \
		jump="DNAT" \
	$PYTHON action-netfilter.py \
2>&1
