#!/bin/sh

export ETC=/opt/scavenger/etc

PYTHONS="python25 python2.5 python"

for P in `echo $PYTHONS`;
do
	PYTHON=`which $P 2> /dev/null`
	if [ ! -z "$PYTHON" ]; then
		break
	fi
done

if [ -z "$PYTHON" ]; then
	echo "no python intepreter found"
	sleep 10
fi

cd /opt/scavenger

#	strace -vfF -o ./strace.txt \
#	/usr/bin/softlimit -m 15000000 \

exec \
	env \
		mta="82.219.2.81" \
	$PYTHON netfilter.py \
2>&1
