#!/bin/sh

if [ ! -d /var/log/scavenger/postfix ]; then
	mkdir -p /var/log/scavenger/postfix
	chown nobody.nogroup /var/log/scavenger/postfix
fi

exec /usr/bin/setuidgid nobody /usr/bin/multilog t s5000000 /var/log/scavenger/postfix
