#!/bin/sh

if [ ! -d /var/log/scavenger/capture/aol ]; then
	mkdir -p /var/log/scavenger/capture/aol
	chown nobody.nogroup /var/log/scavenger/capture/aol
fi

exec /usr/bin/setuidgid nobody /usr/bin/multilog t s5000000 /var/log/scavenger/capture/aol
