#!/bin/sh

export ETC=/opt/mail/etc
export PYTHONPATH=$PYTHONPATH:/opt/lib:/opt/mail/lib

PYTHONS="python25 python2.5 python"

for P in `echo $PYTHONS`;
do
	PYTHON=`which $P 2> /dev/null`
	if [ ! -z "$PYTHON" ]; then
		break
	fi
done

if [ -z "$PYTHON" ]; then
	echo "no python intepreter found"
	sleep 10
fi

cd /opt/scavenger

exec \
	env \
		debug="7" \
		port="25" \
		organisation="Exa Networks" \
		hostname="spam.mail.exa.net.uk" \
		smarthost="smtp.exa-networks.co.uk" \
		roles="abuse postmaster" \
		domains="exa-networks.co.uk exa.net.uk" \
		contact="support@exa-networks.co.uk" \
		limit=50 \
		timeout=60 \
		control="exa" \
		url="http://spam.exa.net.uk/" \
	$PYTHON mta.py \
2>&1
