#!/bin/sh

export ETC=/opt/scavenger/etc
export PYTHONPATH=$PYTHONPATH:/opt/scavenger/lib

PYTHONS="python25 python2.5 python"

for P in `echo $PYTHONS`;
do
	PYTHON=`which $P 2> /dev/null`
	if [ ! -z "$PYTHON" ]; then
		break
	fi
done

if [ -z "$PYTHON" ]; then
	echo "no python intepreter found"
	sleep 10
fi

cd /opt/scavenger/daemon

exec \
	$PYTHON mta.py \
2>&1
