#!/bin/sh

export ETC=/opt/scavenger/etc

PYTHONS="python25 python2.5 python"

for P in `echo $PYTHONS`;
do
	PYTHON=`which $P 2> /dev/null`
	if [ ! -z "$PYTHON" ]; then
		break
	fi
done

if [ -z "$PYTHON" ]; then
	echo "no python intepreter found"
	sleep 10
fi

cd /opt/scavenger

exec \
	env \
		debug="7" \
		port="25254" \
		smarthost="smtp.exa-networks.co.uk" \
		timeout=60 \
		recipient="<thomas.mangin@exa-networks.co.uk> Thomas Mangin" \
	$PYTHON action-mail.py \
2>&1
